language: node_js
node_js:
    - "8"
cache: yarn
install:
    - yarn install
before_script:
    # - "export DISPLAY=:99.0"
    # - "sh -e /etc/init.d/xvfb start"
    # - sleep 3 # give xvfb some time to start
    # - yarn test:int-setup
    - yarn start
script:
    - yarn lint:js
    - yarn lint:scss
    - yarn test:unit
    # - yarn test:int
