language: node_js
node_js:
    - "8"
sudo: required
dist: trusty
addons:
    chrome: stable
cache: yarn
install:
    - yarn install
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - yarn test:int-setup &
    - sleep 3
script:
    - yarn lint:js
    - yarn lint:scss
    - yarn test:unit
    - yarn test:int
    - yarn storybook:build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local-dir: storybook-static
    on:
        branch: master
